
language: erlang
otp_release:
   - 17.0
   - 18.0
   - 18.2
   - 18.2.1
   - 19.0
   - 20.0
   - 21.0
   - 22.0


install:
  - sudo pip install codecov
script:
  - rebar3 compile
  - rebar3 xref
  - rebar3 eunit
  - rebar3 dialyzer
  - rebar3 edoc
  - rebar3 cover
  - rebar3 as test covertool generate
  - cp _build/test/covertool/jsone.covertool.xml ./cobertura.xml

after_success:
  - codecov

script: "sh -ex .travis_build.sh"
